[package]
name = "rust_diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = "0.28" # for window handling
futures = "0.3" # for async functionality used by winit
rand = "0.8" # for random number generation